version: '3'

services:
  nginx117:
    build:
      context: .
      dockerfile: nginx/1.17/Dockerfile
    volumes:
      - ${CODE_FOLDER}:/var/www:${VOLUME_CACHE_OPTION}
      - ./nginx/1.17/sites:/etc/nginx/sites-available
      - ./nginx/1.17/conf:/etc/nginx/conf.d

  php56:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        - BUILD_VERSION=5.6
    volumes:
      - ${CODE_FOLDER}:/var/www:${VOLUME_CACHE_OPTION}
      - ./php/5.6/home:/root:${VOLUME_CACHE_OPTION}
      - ./php/5.6/supervisord:/etc/supervisord.d/usr
      - ./php/5.6/crontabs:/var/spool/cron/crontabs

  php70:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        - BUILD_VERSION=7.0
    volumes:
      - ${CODE_FOLDER}:/var/www:${VOLUME_CACHE_OPTION}
      - ./php/7.0/home:/root:${VOLUME_CACHE_OPTION}
      - ./php/7.0/supervisord:/etc/supervisord.d/usr
      - ./php/7.0/crontabs:/var/spool/cron/crontabs

  php71:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        - BUILD_VERSION=7.1
    volumes:
      - ${CODE_FOLDER}:/var/www:${VOLUME_CACHE_OPTION}
      - ./php/7.1/home:/root:${VOLUME_CACHE_OPTION}
      - ./php/7.1/supervisord:/etc/supervisord.d/usr
      - ./php/7.1/crontabs:/var/spool/cron/crontabs

  php72:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        - BUILD_VERSION=7.2
    volumes:
      - ${CODE_FOLDER}:/var/www:${VOLUME_CACHE_OPTION}
      - ./php/7.2/home:/root:${VOLUME_CACHE_OPTION}
      - ./php/7.2/supervisord:/etc/supervisord.d/usr
      - ./php/7.2/crontabs:/var/spool/cron/crontabs

  php73:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        - BUILD_VERSION=7.3
    volumes:
      - ${CODE_FOLDER}:/var/www:${VOLUME_CACHE_OPTION}
      - ./php/7.3/home:/root:${VOLUME_CACHE_OPTION}
      - ./php/7.3/supervisord:/etc/supervisord.d/usr
      - ./php/7.3/crontabs:/var/spool/cron/crontabs

  php74:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        - BUILD_VERSION=7.4
    volumes:
      - ${CODE_FOLDER}:/var/www:${VOLUME_CACHE_OPTION}
      - ./php/7.4/home:/root:${VOLUME_CACHE_OPTION}
      - ./php/7.4/supervisord:/etc/supervisord.d/usr
      - ./php/7.4/crontabs:/var/spool/cron/crontabs

  mailhog:
    image: mailhog/mailhog

  mysql57:
    build:
      context: .
      dockerfile: mysql/Dockerfile
      args:
        - BUILD_VERSION=5.7
    volumes:
      - ./mysql/5.7/data:/var/lib/mysql
      - ./mysql/5.7/home:/root:${VOLUME_CACHE_OPTION}
    environment:
      - MYSQL_ROOT_PASSWORD=root

  mysql80:
    build:
      context: .
      dockerfile: mysql/Dockerfile
      args:
        - BUILD_VERSION=8.0
    volumes:
      - ./mysql/8.0/data:/var/lib/mysql
      - ./mysql/8.0/home:/root:${VOLUME_CACHE_OPTION}
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis50:
    build:
      context: .
      dockerfile: redis/5.0/Dockerfile
