version: '3'

networks:
  pp-api:

services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/var/www:cached
      - ./nginx/logs:/var/log/nginx
      - ./nginx/sites:/etc/nginx/sites-available
    networks:
      pp-api:
        aliases:
          - local-api.publisherplus.ie
    ports:
      - "80:80"
      - "443:443"

  php56:
    build:
      context: ./php56
    volumes:
      - ../:/var/www:cached
      - ./php56/home:/root:cached
      - ./php56/supervisord:/etc/supervisord.d
    networks:
      - pp-api
      - default

  php70:
    build:
      context: ./php70
    volumes:
      - ../:/var/www:cached
      - ./php70/home:/root:cached
      - ./php70/supervisord:/etc/supervisord.d
    networks:
      - pp-api
      - default

  php72:
    build:
      context: ./php72
    volumes:
      - ../:/var/www:cached
      - ./php72/home:/root:cached
      - ./php72/supervisord:/etc/supervisord.d
    networks:
      - pp-api
      - default

  php73:
    build:
      context: ./php73
    volumes:
      - ../:/var/www:cached
      - ./php73/home:/root:cached
      - ./php73/supervisord:/etc/supervisord.d
    networks:
      - pp-api
      - default
    ports:
      - "7322:22"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  mysql80:
    build:
      context: ./mysql80
    ports:
      - "3307:3306"
    volumes:
      - ./mysql80/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  mysql57:
    image: mysql:5.7
    ports:
      - "3308:3306"
    volumes:
      - ./mysql57/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis:5.0-alpine
