version: '3'

services:
  alpine311:
    build:
      context: .
      dockerfile: alpine/Dockerfile
      args:
        - BUILD_VERSION=3.11
    volumes:
      - ${CODE_FOLDER}:/var/www${VOLUME_CACHE_OPTION}
      - ./alpine/3.11/home:/root${VOLUME_CACHE_OPTION}
      - ./alpine/3.11/supervisord:/etc/supervisord.d/usr
      - ./alpine/3.11/crontabs:/var/spool/cron/crontabs

  nginx117:
    build:
      context: .
      dockerfile: nginx/1.17/Dockerfile
    volumes:
      - ${CODE_FOLDER}:/var/www${VOLUME_CACHE_OPTION}
      - ./nginx/1.17/sites:/etc/nginx/sites-available
      - ./nginx/1.17/conf:/etc/nginx/conf.d
      - ./nginx/1.17/home:/root${VOLUME_CACHE_OPTION}

  php56:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        - BUILD_VERSION=5.6
    volumes:
      - ${CODE_FOLDER}:/var/www${VOLUME_CACHE_OPTION}
      - ./php/5.6/home:/root${VOLUME_CACHE_OPTION}
      - ./php/5.6/supervisord:/etc/supervisord.d/usr
      - ./php/5.6/crontabs:/var/spool/cron/crontabs

  php70:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        - BUILD_VERSION=7.0
    volumes:
      - ${CODE_FOLDER}:/var/www${VOLUME_CACHE_OPTION}
      - ./php/7.0/home:/root${VOLUME_CACHE_OPTION}
      - ./php/7.0/supervisord:/etc/supervisord.d/usr
      - ./php/7.0/crontabs:/var/spool/cron/crontabs

  php71:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        - BUILD_VERSION=7.1
    volumes:
      - ${CODE_FOLDER}:/var/www${VOLUME_CACHE_OPTION}
      - ./php/7.1/home:/root${VOLUME_CACHE_OPTION}
      - ./php/7.1/supervisord:/etc/supervisord.d/usr
      - ./php/7.1/crontabs:/var/spool/cron/crontabs

  php72:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        - BUILD_VERSION=7.2
    volumes:
      - ${CODE_FOLDER}:/var/www${VOLUME_CACHE_OPTION}
      - ./php/7.2/home:/root${VOLUME_CACHE_OPTION}
      - ./php/7.2/supervisord:/etc/supervisord.d/usr
      - ./php/7.2/crontabs:/var/spool/cron/crontabs

  php73:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        - BUILD_VERSION=7.3
    volumes:
      - ${CODE_FOLDER}:/var/www${VOLUME_CACHE_OPTION}
      - ./php/7.3/home:/root${VOLUME_CACHE_OPTION}
      - ./php/7.3/supervisord:/etc/supervisord.d/usr
      - ./php/7.3/crontabs:/var/spool/cron/crontabs

  php74:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        - BUILD_VERSION=7.4
    volumes:
      - ${CODE_FOLDER}:/var/www${VOLUME_CACHE_OPTION}
      - ./php/7.4/home:/root${VOLUME_CACHE_OPTION}
      - ./php/7.4/supervisord:/etc/supervisord.d/usr
      - ./php/7.4/crontabs:/var/spool/cron/crontabs

  mailhog:
    image: mailhog/mailhog

  mysql57:
    build:
      context: .
      dockerfile: mysql/Dockerfile
      args:
        - BUILD_VERSION=5.7
    volumes:
      - ./mysql/5.7/data:/var/lib/mysql
      - ./mysql/5.7/home:/root${VOLUME_CACHE_OPTION}
    environment:
      - MYSQL_ROOT_PASSWORD=root

  mysql80:
    build:
      context: .
      dockerfile: mysql/Dockerfile
      args:
        - BUILD_VERSION=8.0
    volumes:
      - ./mysql/8.0/data:/var/lib/mysql
      - ./mysql/8.0/home:/root${VOLUME_CACHE_OPTION}

  elasticsearch76:
    build:
      context: .
      dockerfile: elasticsearch/Dockerfile
      args:
        - IMAGE_VERSION=7.6.1
        - BUILD_VERSION=7.6
    volumes:
      - ./elasticsearch/7.6/data:/usr/share/elasticsearch/data
      - ./elasticsearch/7.6/home:/root${VOLUME_CACHE_OPTION}

  kibana76:
    image: kibana:7.6.1
    depends_on:
      - elasticsearch76
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch76:9200

  elasticsearch68:
    build:
      context: .
      dockerfile: elasticsearch/Dockerfile
      args:
        - IMAGE_VERSION=6.8.7
        - BUILD_VERSION=6.8
    volumes:
      - ./elasticsearch/6.8/data:/usr/share/elasticsearch/data
      - ./elasticsearch/6.8/home:/root${VOLUME_CACHE_OPTION}

  kibana68:
    image: kibana:6.8.7
    depends_on:
      - elasticsearch68
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch68:9200

  redis50:
    build:
      context: .
      dockerfile: redis/5.0/Dockerfile

  varnish30:
    build:
      context: .
      dockerfile: varnish/Dockerfile
      args:
        - BUILD_VERSION=3.0
    environment:
      - VARNISH_PORT=80
      - VARNISHLOG=true
    volumes:
      - ./varnish/3.0/default.vcl:/etc/varnish/default.vcl

  varnish41:
    build:
      context: .
      dockerfile: varnish/Dockerfile
      args:
        - BUILD_VERSION=4.1
    environment:
      - VARNISH_PORT=80
      - VARNISHLOG=true
    volumes:
      - ./varnish/4.1/default.vcl:/etc/varnish/default.vcl

  varnish52:
    build:
      context: .
      dockerfile: varnish/Dockerfile
      args:
        - BUILD_VERSION=5.2
    environment:
      - VARNISH_PORT=80
      - VARNISHLOG=true
    volumes:
      - ./varnish/5.2/default.vcl:/etc/varnish/default.vcl

  varnish60:
    build:
      context: .
      dockerfile: varnish/Dockerfile
      args:
        - BUILD_VERSION=6.0
    environment:
      - VARNISH_PORT=80
      - VARNISHLOG=true
    volumes:
      - ./varnish/6.0/default.vcl:/etc/varnish/default.vcl

  python35:
    build:
      context: .
      dockerfile: python/Dockerfile
      args:
        - BUILD_VERSION=3.5
    volumes:
      - ${CODE_FOLDER}:/var/www${VOLUME_CACHE_OPTION}
      - ./python/3.5/home:/root${VOLUME_CACHE_OPTION}
      - ./python/3.5/supervisord:/etc/supervisord.d/usr
      - ./python/3.5/crontabs:/var/spool/cron/crontabs

  go114:
    build:
      context: .
      dockerfile: go/Dockerfile
      args:
        - BUILD_VERSION=1.14
    volumes:
      - ${CODE_FOLDER}:/var/www${VOLUME_CACHE_OPTION}
      - ./go/1.14/home:/root${VOLUME_CACHE_OPTION}
      - ./go/1.14/supervisord:/etc/supervisord.d/usr
      - ./go/1.14/crontabs:/var/spool/cron/crontabs
